name: main
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  main:
    name: Build, lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: bahmutov/npm-install@v1
      - run: yarn workspace next-query-params run build
      - run: yarn workspaces run lint
      - run: yarn workspace next-query-params run test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          build: |
            yarn workspace next-query-params run build
            yarn build
          working-directory: packages/example
